image: node:carbon
definitions:
  caches:
    nodemodules: nodemodules
  services:
    docker:
      memory: 3072
testStep: &testStep
  - step:
      name: Default Test Step
      caches:
        - nodemodules
      script:
        - npm ci
        - npm run lint
        - npm test
nodeBuild: &nodeBuild
  - step:
      name: Node Install and Publish
      image: node:carbon
      caches:
        - nodemodules
      script:
        - npm ci
        - npx semantic-release
        - npm run publish
commonBuildAndDeploy: &commonBuildAndDeploy
  name: Build & Deploy
  image: tstrohmeier/awscli:3.6.4
  script:
    - pip install -U awscli
    - eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
    - export LABEL=${AWS_REGISTRY_URL}:${ENVIRONMENT}_${BITBUCKET_BUILD_NUMBER}
    - >
      docker build
      -t $LABEL
      --build-arg ENVIRONMENT=${ENVIRONMENT}
      .
    - docker push $LABEL
    - sed -i -e "s|__LABEL__|$LABEL|g" task-definition.json
    - sed -i -e "s|__ENV__|${ENV}|g" task-definition.json
    - sed -i -e "s|__EXECUTION_ROLE_ARN__|${EXECUTION_ROLE}|g" task-definition.json
    - sed -i -e "s|__TASK_ROLE_ARN__|${TASK_ROLE}|g" task-definition.json
    - sed -i -e "s|__NGINX_REPO__|${NGINX_REPO}|g" task-definition.json 
    - >
      aws ecs register-task-definition
      --family scplus-shared-components
      --cli-input-json file://task-definition.json
    - >
      aws ecs update-service
      --service scplus-shared-components
      --task-definition scplus-shared-components
      --cluster SharedServices
  services:
    - docker
pipelines:
  default:
    - <<: *testStep
  custom:
    production:
      - step:
          deployment: production
          <<: *commonBuildAndDeploy
      - <<: *nodeBuild
  branches:
    master:
      - step:
          deployment: production
          <<: *commonBuildAndDeploy
      - <<: *nodeBuild
