// import all global styles
import './fonts.css';
import './root.css';
import './typography.css';
import './animations.css';
import './legacyAutoGenerated.css';
import './utilClasses.css';
import './materialUIOverrides.css';
import './toastrOverrides.css';
