// import all global styles
import fonts from './styles/fonts.css';
import root from './styles/root.css';
import typography from './styles/typography.css';
import animations from './styles/animations.css';
import legacy from './styles/legacyAutoGenerated.css';
import utilClasses from './styles/utilClasses.css';
import muiOverrides from './styles/materialUIOverrides.css';
import toastrOverrides from './styles/toastrOverrides.css';

// import Components
import Avatar from './components/Avatar';

export default {
  Avatar,
  fonts,
  root,
  typography,
  animations,
  legacy,
  utilClasses,
  muiOverrides,
  toastrOverrides,
};
